# Generated by Django 4.0.3 on 2022-03-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=200)),
                ('r_gender', models.CharField(max_length=200)),
                ('r_age', models.IntegerField()),
                ('r_bloodGroup', models.CharField(max_length=200)),
                ('r_covid_pos_date', models.DateField()),
                ('r_covid_neg_date', models.DateField()),
                ('r_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.city')),
                ('r_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.state')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=200)),
                ('d_gender', models.CharField(max_length=200)),
                ('d_age', models.IntegerField()),
                ('d_bloodGroup', models.CharField(max_length=200)),
                ('d_covid_pos_date', models.DateField()),
                ('d_covid_neg_date', models.DateField()),
                ('d_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.city')),
                ('d_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.state'),
        ),
    ]
