# Generated by Django 4.0.3 on 2022-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='d_city',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='d_state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requester',
            name='r_city',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requester',
            name='r_state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
