# Generated by Django 4.0.3 on 2022-04-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_donor_d_city_alter_donor_d_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='d_city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.city'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='d_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.state'),
        ),
    ]
